    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: my-app

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
      working-directory: my-app